### ISSUE TITLE
Rough status tracker

### ISSUE THREAD

**Issue by cormacrelf** [zotero/citeproc-rs#1]
### Parsing status

- [x] Error highlighting with fix hints like `rustc`'s output
- [x] Semantic version requirement
- [x] Feature flags and gating using `<features><feature name="conditions" /></features>`
- [x] CSL
    - [x] locale blocks, type-checked terms, localised dates
    - [x] type-checked variables as enums
    - [x] citation, layout blocks
    - [x] every rendering element
    - [x] bibliography blocks (currently just ignored)
    - [ ] info blocks (only really needed for dependent styles)
- [ ] CSL-M
    - [x] variable extensions/modifications
    - [x] multi-conditionals
    - [x] institutions
    - [ ] jurisdictions
    - [ ] style modules
    - [ ] macro namespacing? You should probably be able to define new and override existing macros in a juris module, it's a bit limiting without that.
- [ ] Pandoc documents
    - [ ] locators
    - [ ] inline references
- [ ] CSL-JSON and `citeproc-js`-style inputs
    - [x] Numeric parsing (hyphens, ampersands, etc)
    - [x] Date parsing:
        - [x] raw, including ranges
        - [x] date-parts, including ranges
        - [ ] other
    - [x] Reference type
    - [ ] Reference `serde::Deserialize` implementation (currently parses a large Better Bibtex CSL-JSON dump)
        - [x] ids, types
        - [x] names
        - [x] dates
        - [x] strings
        - [ ] micro-HTML syntax
        - [x] parse CSL-JSON with markdown into an intermediate format (see pandoc-preproc)
        - [ ] parse the Pandoc CSL-JSON into References
        - [ ] seasons
    - [x] Cite type
    - [x] Cite `serde::Deserialize` implementation
- [ ] BibTeX (implement as a Haskell pre-processor using the Pandoc parser that compiles BibTeX to an extension of CSL-JSON that can have Pandoc Inlines instead of strings.)

### IR Generation status (see design document for what this is)

- [x] Affixes, formatting in general
- [x] Delimiters, generally
- [ ] text-case, in general
- [ ] strip-periods, in general
- [ ] Quotes
    - [x] Kinda basic pandoc Quoted inlines with flip-flop on output phase
    - [ ] ...
- [x] Conditionals
- [x] Macros
    - [x] Basics
    - [x] Macro recursion avoidance
- [x] Groups
    - [x] Basics
    - [x] called-but-didn't-render-any-variables
- [x] Names
    - [x] latin/cyrillic detection
    - [x] ordering of name parts, and collapsing delimiters where parts were None
    - [x] form="long" and "short"
    - [x] name-as-sort-order
    - [x] et-al-min, et-al-use-first
    - [x] et al in subsequent references
    - [x] et-al-use-first (the ... feature)
    - [x] and (basic)
    - [x] delimiter-precedes-last
    - [x] delimiter-precedes-et-al
    - [x] inheritable attributes merging
    - [x] initialize, initialize-with, innitialize-with-hyphen
    - [x] using terms for all the customizable bits, like and
    - [x] actually inheriting attributes
    - [x] name-part formatting
- [ ] Institutions
    - [ ] like anything at all on that front
- [ ] Dates
    - [x] Independent dates
    - [x] Defining locale dates
    - [x] Calling localized dates
    - [x] Delimiters, affixes
    - [ ] Use of terms like month and season, and range delimiters
    - [ ] Date ranges
- [ ] Variables
    - [x] Text variables
    - [x] Number variables
    - [x] Locator types
    - [ ] Numeric ordinals
    - [x] Term fallbacks
- [ ] Output modules for pandoc and text
    - [x] citations (well, it's evolving, but it works mostly)
    - [ ] bibliography support
- [ ] Many other things

### IR disambiguation and post-processing

- [x] DisambToken and inverted index of available references
- [ ] DisambToken for names (trickier; see discussion)
- [ ] Falling back to comparing full IR against each matching reference to check differences
- [ ] add names
- [ ] add given names, & only as many as necessary
    - [ ] 'all-names' (and similar) inverted index applied to each rendered name in the entire document
- [ ] YearSuffixHook::Date
- [x] YearSuffixHook::Explicit
- [x] Re-rendering with disambiguate="true"
- [x] Re-rendering in 4 stages by mutating cloned IR, depending on the style, and short-out if-unambiguous

[Some discussion here](https://github.com/cormacrelf/citeproc-rs/blob/master/docs/disambiguation.md).

### Infrastructure

Incremental processing using Salsa is semi-blocked on Salsa supporting generics in its query groups and storage. I'm helping out where I can. It will be pretty awesome once that's off the ground. It's already in use for locale fetch+merge, and works like a charm.

- [x] Locale fetching
  - [x] Locale fallback order
  - [x] Locale parsing
  - [x] Reading from a directory with `locale-en-US.xml` file naming scheme
  - [x] Locale merging
    - [x] terms (per form)
    - [x] ordinals (all at once)
    - [x] options
    - [x] dates
  - [x] Access to merged locales from processing code
- [ ] Style module fetching / search paths
- [ ] Juris abbreviations
- [ ] Dependent styles
- [x] Pandoc filter mode
    - [x] Read clusters into the db, and write them back out again
    - [x] Basic JSON filtering CLI
    - [x] Recognise STDIN and run in filter mode automatically
    - [x] Support pandoc metadata for configuration

See README for example usage; also run `cargo run -- --help`.

**Comment by iansampson** [comment]
Awesome, really excited about this project. There’s definitely a need for a robust alternative to citeproc-js and pandoc citeproc. I’m aware that the codebase is evolving pretty rapidly, but if you’re looking for other contributors I might be able to help. (I thought about building my own CSL processor in Swift for a Markdown app I’m working on, but a platform-agnostic library makes much more sense, especially since the spec lacks a reliable reference implementation.)

**Comment by iansampson** [comment]
Sounds good – thanks for all the info. You’re right: I’m pretty new to Rust, and working my way through the book right now. It’ll probably be a couple weeks at least before I’ve got enough of a handle on the language to make any significant changes. In the meantime, I’m just reading through the codebase and familiarizing myself with how everything works.

And yes, I really need to get some things up on my GitHub profile! I have nine private Swift repos in there (including production code for an app that’s in TestFlight beta) but I‘ve been a bit shy about making them public. I’ve been writing Swift for a couple years (and not just iOS: the Markdown parser for my next app works directly on buffers of UTF8 code units so I’m no stranger to memory allocation), so I actually feel quite at home in Rust. So far, anyway.

As for the tasks you listed, the first thing I’d take a stab at (if you don’t get to it first) is building some infrastructure for incorporating the CSL test suite (omitting all the citeproc.js-specific tests for now). I’m a stickler for unit tests (which are strangely uncommon in Swift development) and I think that’d be a good way to get my feet wet without touching the core code. Also, if there’s any non-programming tasks I could do while I’m brushing up on Rust, that’d be another place to start: for example, researching undocumented variables in the CSL and CSL-M styles that cause parse errors, or writing documentation/comments.

**Comment by cormacrelf** [comment]
The test suite would be great. (Keep in mind that cargo may be getting a data-driven test runner solution. I can’t remember where the RFCs are up to on that.) The suite should be a submodule, and although you can depend on python to run the “human” to JSON conversion, although it would be nice to avoid both the dependency and the build step by just parsing and running straight out of a humans file, since most sections are just JSON anyway. I will shortly give you some more APIs to work with, like `Driver::load_library(self, json: &str)` and `Driver::include_uncited(self, ids: Vec<ID>)` and a batch cite processor or whatever.

The CSL-M clarity kinda has to wait until @fbennett comes back online. It appears from the citeproc-js issues page that he’s been AFK for a bit.

**Comment by fbennett** [comment]
This comment gave me a thought:
> * There are tests in there that depend on citeproc-js' incremental adjustments and internals, unfortunately (eg anything with [this](https://github.com/citation-style-language/test-suite#citations)) so those would have to be skipped until an incremental mode exists using the new

Many of the tests with the CITATIONS segment didn't actually exercise incremental processing. I did a quick check by refactoring all tests of that type to the simpler input form and rerunning them. Sure enough, 154 of them still passed just fine, so I reverted the remaining 46 that failed, and [pushed the revisions](https://github.com/citation-style-language/test-suite/commit/f1dd8ad89a42fe8d7ec25f88e398c0f93e30deef) to the ``test-suite`` repo.

A quick look at the failures suggests that many of those don't fail for anything inherent in the input, but because the ``citeproc-js`` method used to run the simpler form lacks support for the sorting of citations. So we can push the simplification a little further still when that's fixed.

**Comment by chriskrycho** [comment]
Hello! I'm *delighted* to see that you're doing this: I initially planned to start trying to do this myself almost four years ago, got, uhh, a bit [sidetracked](https://newrustacean.com), and now am back at my original motivations for doing it. If there's any way I can help—including when you've gotten it to a more stable point—please let me know. I'm aiming to be investing 6–12 hours a week into the project for which I've been wanting this going forward, and I'm *very* happy to devote some of those hours to this.

**Comment by chriskrycho** [comment]
(To elaborate on the above: I *did* read the lengthy comment above, but I *don't* want to step on anyone else's ongoing efforts!)
